/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BilletterieRouteImport } from './routes/billetterie'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FormationRouteImport } from './routes/formation'
import { Route as LeClubRouteImport } from './routes/le-club'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ActualitesIndexRouteImport } from './routes/actualites.index'
import { Route as ActualitesSlugRouteImport } from './routes/actualites.$slug'
import { Route as EffectifsIndexRouteImport } from './routes/effectifs.index'
import { Route as EffectifsSlugRouteImport } from './routes/effectifs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BilletterieRoute = BilletterieRouteImport.update({
  id: '/billetterie',
  path: '/billetterie',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationRoute = FormationRouteImport.update({
  id: '/formation',
  path: '/formation',
  getParentRoute: () => rootRouteImport,
} as any)
const LeClubRoute = LeClubRouteImport.update({
  id: '/le-club',
  path: '/le-club',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsRoute = ResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectifsIndexRoute = EffectifsIndexRouteImport.update({
  id: '/effectifs/',
  path: '/effectifs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectifsSlugRoute = EffectifsSlugRouteImport.update({
  id: '/effectifs/$slug',
  path: '/effectifs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billetterie': typeof BilletterieRoute
  '/calendrier': typeof CalendrierRoute
  '/contact': typeof ContactRoute
  '/formation': typeof FormationRoute
  '/le-club': typeof LeClubRoute
  '/partenaires': typeof PartenairesRoute
  '/resultats': typeof ResultatsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/effectifs/$slug': typeof EffectifsSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/effectifs/': typeof EffectifsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billetterie': typeof BilletterieRoute
  '/calendrier': typeof CalendrierRoute
  '/contact': typeof ContactRoute
  '/formation': typeof FormationRoute
  '/le-club': typeof LeClubRoute
  '/partenaires': typeof PartenairesRoute
  '/resultats': typeof ResultatsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/effectifs/$slug': typeof EffectifsSlugRoute
  '/actualites': typeof ActualitesIndexRoute
  '/effectifs': typeof EffectifsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billetterie': typeof BilletterieRoute
  '/calendrier': typeof CalendrierRoute
  '/contact': typeof ContactRoute
  '/formation': typeof FormationRoute
  '/le-club': typeof LeClubRoute
  '/partenaires': typeof PartenairesRoute
  '/resultats': typeof ResultatsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/effectifs/$slug': typeof EffectifsSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/effectifs/': typeof EffectifsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billetterie'
    | '/calendrier'
    | '/contact'
    | '/formation'
    | '/le-club'
    | '/partenaires'
    | '/resultats'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/effectifs/$slug'
    | '/actualites/'
    | '/effectifs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billetterie'
    | '/calendrier'
    | '/contact'
    | '/formation'
    | '/le-club'
    | '/partenaires'
    | '/resultats'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/effectifs/$slug'
    | '/actualites'
    | '/effectifs'
  id:
    | '__root__'
    | '/'
    | '/billetterie'
    | '/calendrier'
    | '/contact'
    | '/formation'
    | '/le-club'
    | '/partenaires'
    | '/resultats'
    | '/sitemap.xml'
    | '/actualites/$slug'
    | '/effectifs/$slug'
    | '/actualites/'
    | '/effectifs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BilletterieRoute: typeof BilletterieRoute
  CalendrierRoute: typeof CalendrierRoute
  ContactRoute: typeof ContactRoute
  FormationRoute: typeof FormationRoute
  LeClubRoute: typeof LeClubRoute
  PartenairesRoute: typeof PartenairesRoute
  ResultatsRoute: typeof ResultatsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  EffectifsSlugRoute: typeof EffectifsSlugRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
  EffectifsIndexRoute: typeof EffectifsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billetterie': {
      id: '/billetterie'
      path: '/billetterie'
      fullPath: '/billetterie'
      preLoaderRoute: typeof BilletterieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation': {
      id: '/formation'
      path: '/formation'
      fullPath: '/formation'
      preLoaderRoute: typeof FormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/le-club': {
      id: '/le-club'
      path: '/le-club'
      fullPath: '/le-club'
      preLoaderRoute: typeof LeClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats': {
      id: '/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof ResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effectifs/': {
      id: '/effectifs/'
      path: '/effectifs'
      fullPath: '/effectifs/'
      preLoaderRoute: typeof EffectifsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effectifs/$slug': {
      id: '/effectifs/$slug'
      path: '/effectifs/$slug'
      fullPath: '/effectifs/$slug'
      preLoaderRoute: typeof EffectifsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BilletterieRoute: BilletterieRoute,
  CalendrierRoute: CalendrierRoute,
  ContactRoute: ContactRoute,
  FormationRoute: FormationRoute,
  LeClubRoute: LeClubRoute,
  PartenairesRoute: PartenairesRoute,
  ResultatsRoute: ResultatsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ActualitesSlugRoute: ActualitesSlugRoute,
  EffectifsSlugRoute: EffectifsSlugRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
  EffectifsIndexRoute: EffectifsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
